version: '3.8'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      env_file: .env.docker
      NODE_ENV: production
